import { Card, Container, Grid, Typography } from "@mui/material";
import Head from "next/head";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h1">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Typography>

        <Typography variant="body1" component="p">
          Get started by editing <code>pages/index.tsx</code>
        </Typography>
      </main>

      <footer>footer</footer>
    </Container>
  );
};

export default Home;
